name: Cmake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev zlib1g-dev libtinyxml2-dev 
    - name: build-dir
      run: mkdir build
    - name: cmake
      working-directory: ./build
      run: cmake ..
    - name: make
      working-directory: ./build
      run: make -j2
    - name: list
      run: ls build

# See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
# for the number of runners
