name: Cmake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev zlib1g-dev libtinyxml2-dev 
    - name: configure
      run: mkdir build && cd build
    - name: cmake
      run: ls .. && cmake ..
    - name: make
      run: make -j2

# See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
# for the number of runners
