name: Cmake CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev zlib1g-dev libtinyxml2-dev 
    - name: cmake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'default'
        buildPreset: 'default'
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-build
        path: |
          build
          !build/CMakeCache.txt
          !build/build.ninja
          !build/_deps
          !build/cmake_install.cmake
          !build/*.a

# See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
# for the number of runners
